<a href="https://colab.research.google.com/github/iznue/Mtvs/blob/main/practice12_RegressionModeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine Learning with Python 
### 실습01.Regression Modeling

1. Load Data & Explore Data
2. Preprocess Data
3. Model Train
4. Model Test
5. Model Evaluate

In [1]:
# 1. Load Data & Explore Data
import pandas as pd

data = pd.read_csv('5강_데이터_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
data.describe(include='all') # object type인 state도 출력하기 위해 include 옵션 설정

R&D Spend  Administration  Marketing Spend     State  \
count       50.000000       50.000000        50.000000        50   
unique            NaN             NaN              NaN         3   
top               NaN             NaN              NaN  New York   
freq              NaN             NaN              NaN        17   
mean     73721.615600   121344.639600    211025.097800       NaN   
std      45902.256482    28017.802755    122290.310726       NaN   
min          0.000000    51283.140000         0.000000       NaN   
25%      39936.370000   103730.875000    129300.132500       NaN   
50%      73051.080000   122699.795000    212716.240000       NaN   
75%     101602.800000   144842.180000    299469.085000       NaN   
max     165349.200000   182645.560000    471784.100000       NaN   

               Profit  
count       50.000000  
unique            NaN  
top               NaN  
freq              NaN  
mean    112012.639200  
std      40306.180338  
min      14681.400000  
25%      90138.902500  
50%     107978.190000  
75%     139765.977500  
max     192261.830000

In [12]:
# 2. Preprocess Data

# X / y 분리
#X = data[['R&D Spend', 'Administration','Marketing Spend','State']]
#y = data['Profit']
# 위 방법은 비효율적이므로 데이터의 인덱스를 이용해 location 지정

X = data.iloc[:, 0:5].values # or [:, :-1]
y = data.iloc[:,-1].values # 바로 numpy 형태로 받기 위해 .values를 붙여줌
# 사용하려는 모델이 숫자만 인식하므로 문자를 변경하는 작업을 수행해야함

print(X[:5])
print(y[:5])

[[165349.2 136897.8 471784.1 'New York' 192261.83]
 [162597.7 151377.59 443898.53 'California' 191792.06]
 [153441.51 101145.55 407934.54 'Florida' 191050.39]
 [144372.41 118671.85 383199.62 'New York' 182901.99]
 [142107.34 91391.77 366168.42 'Florida' 166187.94]]
[192261.83 191792.06 191050.39 182901.99 166187.94]


In [13]:
# one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],
                       remainder='passthrough')
# transformer 이름 : encoder, onehotencoder 기능 사용, 3번째 인덱스를 onehotencoding함
# remainder -> 남은 columns는 살려둠

X = ct.fit_transform(X)
print(X[:5])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1 192261.83]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53 191792.06]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54 191050.39]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62 182901.99]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42 166187.94]]


In [14]:
# 데이터를 train와 test로 나눔
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=9)
# 8:2 비율로 나눔
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40, 7)
(10, 7)
(40,)
(10,)


In [23]:
# 3. Model Train
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)
# 학습 진행

LinearRegression()

In [24]:
# 4. Model Test
y_predict = regressor.predict(X_test)
print(y_test)
print(y_predict)
# 모델의 예측값과 실제 데이터 비교

[111313.02  89949.14 191050.39 132602.65  65200.33 155752.6  129917.04
 118474.03  97427.84 107404.34]
[111313.02  89949.14 191050.39 132602.65  65200.33 155752.6  129917.04
 118474.03  97427.84 107404.34]


In [25]:
# 5. Model Evaluate 
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_predict)
mse = mean_squared_error(y_test, y_predict, squared=False) # squred=False 설정을 하면 루트를 씌운 값이 나옴
r2 = r2_score(y_test, y_predict)

print(mae) # error에 절댓값을 씌운 평균
print(mse) # error에 제곱을 한 평균
print(r2)
# 값이 낮을수록 좋은 모델이라 예측

1.746229827404022e-11
6.352747104407253e-22
1.0


In [26]:
# 6. 모델 확인
# y = w1x1 + w2x2 + w3x3...

print(regressor.coef_)
# 각 독립변수의 w(weight)값을 구할 수 있음

[-1.33604757e-12 -1.86741178e-11  2.00100152e-11 -3.95516953e-16
 -2.63677968e-16  1.11022302e-16  1.00000000e+00]
