<a href="https://colab.research.google.com/github/iznue/Mtvs/blob/main/practice13_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Deep Learning with PyTorch 
### 실습04. Perceptron Modeling : AND Function

1. Prepare Dataset 
2. Train Model
3. Test Model

  
<img src="https://dl.dropbox.com/s/enqqtqnegzb6ceg/and.png" width="400"/>

#### 1. Prepare Data

In [1]:
# 1-1. 데이터 준비

# data : tensor type

import torch

X = torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]])
y = torch.FloatTensor([[0],[0],[0],[1]])

print(X)
print(y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [3]:
# 1-2. 데이터 확인

print(X.shape)
print(y.shape)

torch.Size([4, 2])
torch.Size([4, 1])


#### 2. Train Model

* Design Network : 어떤 레이어, 몇층의 레이어, 각 레이어 몇 노드
* Loss Func & Optimizer
* Train Loop (Forward, back, update)

In [13]:
# 2-1. Network

import torch.nn as nn

linear = nn.Linear(2, 1) # 데이터의 개수가 아니라 하나의 샘플에 들어있는 feature
# 데이터 개수가 아닌 하나의 샘플에 들어있는 feature 입력
# 모든 output은 activation layer를 가짐 -> 활성함수 : sigmoid
# sigmoid를 미분했을 때 도함수의 최댓값은 0.2를 조금 넘음
# 역전파 시 chain-rule을 이용해 미분이 여러번 일어나게 되는데
# 이때 sigmoid를 미분한 값이 너무 작아서 gradient가 뒤로 갈수록 사라지는 vanishing gradient가 발생함
# 따라서 최근은 RuLU함수를 이용함 (은닉층)
sigmoid = nn.Sigmoid() # activation func

# 순차적 계층으로 모델 정의
model = nn.Sequential(linear,
                      sigmoid)
# 순차적으로 가지고있는 module(layer, activation function)을 쌓아줌
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)


In [14]:
# 2-2. Loss Function & Optimizer

loss_fn = nn.BCELoss() # for binary classification
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [15]:
# 2-3. Train Loop

for step in range(100):
  output = model(X) # 모델이 계산한 값: forward propagation

  loss = loss_fn(output, y) # cost 값 계산

  optimizer.zero_grad() # gradient 0 초기화 -> backpropagation에서 계산된 기울기 값이 계속 누적되므로
  loss.backward() # backpropagation weight가 loss에 얼마나 영향을 끼치는지 gradient 계산
  optimizer.step() # weight update

  if step % 10 == 0:
    print(step, loss.item())

0 0.7722126245498657
10 0.5102237462997437
20 0.3892797827720642
30 0.3181474506855011
40 0.27081748843193054
50 0.23658904433250427
60 0.2104177474975586
70 0.1896180510520935
80 0.17261669039726257
90 0.15842168033123016


#### 3. Test Model

In [16]:
# 3. Test

test_tensor = torch.FloatTensor([[1,1], [1,0], [0,1]])

with torch.no_grad(): # 학습이 아닌 평가를 위한 것이므로 gradient 저장하지 않음
  output = model(test_tensor)
  print(output)  # 첫번째 [1,1]은 둘다 1이므로 0.5이상이 나와야함

tensor([[0.7822],
        [0.1525],
        [0.1524]])


In [17]:
print(model.parameters())

<generator object Module.parameters at 0x7fa7f62d1620>
